/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: 6869bca647dd0dc2fb6428b61740fa66)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	CF_ACCOUNT_ID: string;
	ADMIN_READ: Service /* entrypoint AdminRead from ai-investment-collector */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID">> {}
}
